version: '3.8'

services:
  backend:
    build: ./backend
    command: bash -c "
      ./app"
    ports:
      - 8000:8000
    env_file:
      - .env

  frontend:
    build: ./frontend_v2
    depends_on:
      - backend
    ports:
      - 5173:5173
    environment:
      - VITE_PORT=5173
    env_file:
      - .env